"""Message database model."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional


@dataclass
class MessageDO:
    """
    Abstract message data object - maps to messages table.

    Designed to be flexible for different code tools (Claude Code, OpenCode, etc.)
    Each tool may have different message structures.

    Example message types:
    - "user": User input message
    - "assistant": AI assistant response
    - "queue-operation": Internal queue operations
    - "system": System-level messages

    The content field stores the actual message payload as JSON,
    which can vary based on the message type and source tool.
    """

    conversation_id: str
    worker_id: str
    message_type: str  # user, assistant, queue-operation, system, etc.
    uuid: str  # Source's unique identifier for this message
    content: Dict[str, Any]  # Flexible JSON content, structure varies by type
    timestamp: datetime = field(default_factory=datetime.utcnow)
    id: Optional[int] = None  # Auto-generated by database
