"""Message database model."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional


@dataclass
class MessageDO:
    """Message data object - maps to messages table."""

    conversation_id: str
    worker_id: str
    role: str
    content: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)
    id: Optional[int] = None  # Auto-generated by database
